// Generated by: grade_v2.py
// Generated on: 2025-06-13 11:58:24

#pragma once

#include "my_mapper/my_mapper_v2/cost/cost_entropy.hpp"
#include "my_mapper/my_mapper_v2/cost/cost_sensitivity.hpp"
#include "my_mapper/my_mapper_v2/cost/cost_determinacy.hpp"
#include "my_mapper/my_mapper_v2/cost/cost_monotonicity.hpp"
#include "my_mapper/my_mapper_v2/cost/cost_branch.hpp"
#include "my_mapper/my_mapper_v2/cost/cost_num.hpp"
#include "my_mapper/my_mapper_v2/cost/cost_conflict.hpp"
